name: discover-links
on: workflow_dispatch
jobs:
  find:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - run: pip install -r requirements.txt && python discover.py de-de it-it es-es nl-nl nl-be fr-be de-at pt-pt de-ch
